# Generated by Django 2.2.13 on 2020-07-04 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_votes_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='votes_total',
            field=models.IntegerField(default=1),
        ),
    ]
