# Generated by Django 2.2.13 on 2020-07-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_votes_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='votes_total',
        ),
    ]
