# Generated by Django 2.2.13 on 2020-07-07 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0009_remove_product_votes_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='voters',
            field=models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
