# Generated by Django 2.2.13 on 2020-07-07 07:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200707_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='voters',
            field=models.ManyToManyField(related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
