# Generated by Django 2.2.13 on 2020-07-07 08:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_pizza_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='test_users',
            field=models.ManyToManyField(related_name='test_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
