# Generated by Django 2.2.13 on 2020-07-07 11:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_auto_20200707_0818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='voters',
        ),
        migrations.AddField(
            model_name='product',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted', to=settings.AUTH_USER_MODEL),
        ),
    ]
