# Generated by Django 2.2.13 on 2020-07-07 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200707_1120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
